[2023-06-08T12:58:50.972+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.insert_into_table manual__2023-06-08T12:58:49.021479+00:00 [queued]>
[2023-06-08T12:58:50.979+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.insert_into_table manual__2023-06-08T12:58:49.021479+00:00 [queued]>
[2023-06-08T12:58:50.980+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-08T12:58:50.980+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-08T12:58:50.981+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-08T12:58:50.990+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-08 12:58:49.021479+00:00
[2023-06-08T12:58:50.996+0000] {standard_task_runner.py:55} INFO - Started process 773 to run task
[2023-06-08T12:58:50.999+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_postgres', 'insert_into_table', 'manual__2023-06-08T12:58:49.021479+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/postgress_db.py', '--cfg-path', '/tmp/tmpu2x06epy']
[2023-06-08T12:58:51.000+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask insert_into_table
[2023-06-08T12:58:51.058+0000] {task_command.py:388} INFO - Running <TaskInstance: database_postgres.insert_into_table manual__2023-06-08T12:58:49.021479+00:00 [running]> on host 54f992379a81
[2023-06-08T12:58:51.111+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_postgres
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T12:58:49.021479+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-08T12:58:49.021479+00:00
[2023-06-08T12:58:51.112+0000] {sql.py:254} INFO - Executing: INSERT INTO USERS(id,name,email,phone,address,organization) VALUES
            (1,'rahul', 'rahulksh@gmail.com','+9187345632','bihar', 'sigmoid'),
            (2,'shubham','rshuh@gmail.com','+917938535736','hyderabad','amazon'),
            (3,'pankaj','pankajksh@gmail.com','+917838895736','bihar','apple'),
            (4,'raj','rajkumar@gmail.com','+916783456890','ranchi','aidash');
[2023-06-08T12:58:51.120+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-08T12:58:51.223+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-08T12:58:51.227+0000] {sql.py:375} INFO - Running statement: INSERT INTO USERS(id,name,email,phone,address,organization) VALUES
            (1,'rahul', 'rahulksh@gmail.com','+9187345632','bihar', 'sigmoid'),
            (2,'shubham','rshuh@gmail.com','+917938535736','hyderabad','amazon'),
            (3,'pankaj','pankajksh@gmail.com','+917838895736','bihar','apple'),
            (4,'raj','rajkumar@gmail.com','+916783456890','ranchi','aidash');, parameters: None
[2023-06-08T12:58:51.229+0000] {sql.py:384} INFO - Rows affected: 4
[2023-06-08T12:58:51.239+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=database_postgres, task_id=insert_into_table, execution_date=20230608T125849, start_date=20230608T125850, end_date=20230608T125851
[2023-06-08T12:58:51.291+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-06-08T12:58:51.308+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
